server:
  port: 8888

#eureka:
#  instance:
#    hostname: configserver
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RouGang/config-server
          search-paths: test
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone:  http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
