server:
  port: 8881

eureka:
  instance:
     prefer-ip-address: true
     lease-expiration-duration-in-seconds: 30
     lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone:  http://eureka1:8761/eureka/,http://eureka2:8762/eureka/


sample:
    zipkin:
      enabled: false
      base-url: http://localhost:9411

spring:
    boot:
      admin:
        url: http://localhost:8080
