spring.application.name: admin-ui
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone:  http://eureka1:8761/eureka/,http://eureka2:8762/eureka/


spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream


anagement.security.enabled: false

spring.boot.admin.turbine:
  clusters: default
  #location: turbine
  url: http://localhost:8031/turbine.stream

